server:
  servlet:
    context-path: /core
spring:
  redis:
    timeout: 30000
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
logging:
  level:
    org.springframework.transaction: debug
    org.springframework.jdbc: debug
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
