version: '3.5'
services:
  redis-cluster:
    image: redis:6.2.13
    command: redis-cli -a 123456  --cluster create  172.25.104.116:7361 172.25.104.116:7362 172.25.104.116:7363 172.25.104.116:7364 172.25.104.116:7365 172.25.104.116:7366 --cluster-replicas 1  --cluster-yes
    depends_on:
      - cluster-redis-1
      - redis-2
      - redis-3
      - redis-4
      - redis-5
      - redis-6
  cluster-redis-1:
    image: redis:6.2.13
    container_name: cluster-redis-1
#    restart: always
    ports:
      - 7361:7361
      - 17361:17361
    networks:
      - kylin-net
    volumes:
      - redis_1_data:/data
      - /Users/bijian/software/redis/cluster_compose/node-1/conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server","/usr/local/etc/redis/redis.conf"]
  redis-2:
    image: redis:6.2.13
    container_name: redis-2
#    restart: always
    ports:
      - 7362:7362
      - 17362:17362
    networks:
      - kylin-net
    volumes:
      - redis_2_data:/data
      - /Users/bijian/software/redis/cluster_compose/node-2/conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server","/usr/local/etc/redis/redis.conf" ]
  redis-3:
    image: redis:6.2.13
    container_name: redis-3
#    restart: always
    ports:
      - 7363:7363
      - 17363:17363
    networks:
      - kylin-net
    volumes:
      - redis_3_data:/data
      - /Users/bijian/software/redis/cluster_compose/node-3/conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server","/usr/local/etc/redis/redis.conf" ]
  redis-4:
    image: redis:6.2.13
    container_name: redis-4
#    restart: always
    ports:
      - 7364:7364
      - 17364:17364
    networks:
      - kylin-net
    volumes:
      - redis_4_data:/data
      - /Users/bijian/software/redis/cluster_compose/node-4/conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server","/usr/local/etc/redis/redis.conf" ]
  redis-5:
    image: redis:6.2.13
    container_name: redis-5
#    restart: always
    ports:
      - 7365:7365
      - 17365:17365
    networks:
      - kylin-net
    volumes:
      - redis_5_data:/data
      - /Users/bijian/software/redis/cluster_compose/node-5/conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server","/usr/local/etc/redis/redis.conf" ]
  redis-6:
    image: redis:6.2.13
    container_name: redis-6
#    restart: always
    ports:
      - 7366:7366
      - 17366:17366
    networks:
      - kylin-net
    volumes:
      - redis_6_data:/data
      - /Users/bijian/software/redis/cluster_compose/node-6/conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server","/usr/local/etc/redis/redis.conf" ]

volumes:
  redis_1_data:
    driver: local
  redis_2_data:
    driver: local
  redis_3_data:
    driver: local
  redis_4_data:
    driver: local
  redis_5_data:
    driver: local
  redis_6_data:
    driver: local
networks:
  kylin-net:
    driver: bridge
    name: kylin-net