global:
  scrape_interval:     60s
  evaluation_interval: 60s

scrape_configs:

  - job_name: prometheus_job
    static_configs:
      - targets: ['localhost:9090']
        labels:
          instance: prometheus

  - job_name: node_exporter_job
    static_configs:
      - targets: ['c-node-exporter:9100']
        labels:
          instance: localhost

  - job_name: cadvisor_job
    static_configs:
      - targets: ['c-cadvisor:8080']
        labels:
          instance: cAdvisor

  - job_name: mysqld_exporter_job
    static_configs:
      - targets: ['c-mysqld-exporter:9104']
        labels:
          instance: mysql-exporter
