logging:
  level:
    org.springframework.transaction: debug
    org.springframework.jdbc: debug
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
kplat:
  storage:
    s3:
      url: "http://47.94.98.98:9000"
      accessKey: "bijian"
      secretKey: "bja0925bja"