server:
  servlet:
    context-path: /storage
logging:
  level:
    org.springframework.transaction: debug
    org.springframework.jdbc: debug
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
kplat:
  storage:
    type: minio
    s3:
      bucket: bijian
      url: "http://127.0.0.1:9000"
      accessKey: "bijian"
      secretKey: "bja0925bja"
      connectTimeout: 100000
      readTimeOut: 600000