server:
  port: 8001 #服务注册中心端口号
eureka:
  instance:
    hostname: localhost #服务注册中心IP地址
  #  server:
  #1.关闭注册中心自我保护机制
  #    enable-self-preservation: false
  #2.注册中心清理间隔（单位毫秒，默认60*1000）
  #    eviction-interval-timer-in-ms: 10000
  client:
    registerWithEureka: false #是否向服务注册中心注册自己
    fetchRegistry: false #是否检索服务
    serviceUrl: #服务注册中心的配置内容，指定服务注册中心的位置
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/