spring:
  config:
    activate:
      on-profile: local
    import:
      - optional:nacos:plat-common.yaml
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        namespace: local

      discovery:
        server-addr: 127.0.0.1:8848
        namespace: local
#  redis:
#    timeout: 30000
#    database: 0
#    host: 127.0.0.1
#    port: 6379
#    password: 123456
#    cluster:
#      nodes:
#        - 192.168.0.105:7361
#        - 192.168.0.105:7362
#        - 192.168.0.105:7363
#        - 192.168.0.105:7364
#        - 192.168.0.105:7365
#        - 192.168.0.105:7366
#        - 172.25.104.116:7361
#        - 172.25.104.116:7362
#        - 172.25.104.116:7363
#        - 172.25.104.116:7364
#        - 172.25.104.116:7365
#        - 172.25.104.116:7366
    lettuce:
      pool:
        # 连接池中的最大空闲连接 默认8
        max-idle: 8
        # 连接池中的最小空闲连接 默认0
        min-idle: 0
        # 连接池最大连接数 默认8 ，负数表示没有限制
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
        max-wait: -1
#    redisson:
#      config: |
#        clusterServersConfig:
#          idleConnectionTimeout: 10000
#          connectTimeout: 10000
#          timeout: 3000
#          retryAttempts: 3
#          retryInterval: 1500
#          failedSlaveReconnectionInterval: 3000
#          failedSlaveCheckInterval: 60000
#          password: 123456
#          subscriptionsPerConnection: 5
#          clientName: null
#          loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
#          subscriptionConnectionMinimumIdleSize: 1
#          subscriptionConnectionPoolSize: 50
#          slaveConnectionMinimumIdleSize: 24
#          slaveConnectionPoolSize: 64
#          masterConnectionMinimumIdleSize: 24
#          masterConnectionPoolSize: 64
#          readMode: "SLAVE"
#          subscriptionMode: "SLAVE"
#          nodeAddresses:
#          - "redis://172.25.104.116:7361"
#          - "redis://172.25.104.116:7362"
#          - "redis://172.25.104.116:7363"
#          scanInterval: 1000
#          pingConnectionInterval: 0
#          keepAlive: false
#          tcpNoDelay: false
#        threads: 16
#        nettyThreads: 32
#        codec: !<org.redisson.codec.MarshallingCodec> {}
#        transportMode: "NIO"