version: '3.5'
services:
  cluster-init:
    image: redis:6.2.13
    command: redis-cli -a 123456  --cluster create  ${REDIS_IP}:7361 ${REDIS_IP}:7362 ${REDIS_IP}:7363 ${REDIS_IP}:7364 ${REDIS_IP}:7365 ${REDIS_IP}:7366 --cluster-replicas 1  --cluster-yes
    env_file:
      - redis.env
    depends_on:
      - cluster-redis-1
      - cluster-redis-2
      - cluster-redis-3
      - cluster-redis-4
      - cluster-redis-5
      - cluster-redis-6
  cluster-redis-1:
    image: redis:6.2.13
    container_name: cluster-redis-1
#    restart: always
    ports:
      - 7361:7361
      - 17361:17361
    networks:
      - kylin-net
    volumes:
      - redis_1_data:/data
      - ./conf/node-1/conf:/opt/redis/conf
      - ./bin:/opt/redis/bin
    command: ["/opt/redis/bin/start.sh"]
    env_file:
      - redis.env
  cluster-redis-2:
    image: redis:6.2.13
    container_name: cluster-redis-2
#    restart: always
    ports:
      - 7362:7362
      - 17362:17362
    networks:
      - kylin-net
    volumes:
      - redis_2_data:/data
      - ./conf/node-2/conf:/opt/redis/conf
      - ./bin:/opt/redis/bin
    command: ["/opt/redis/bin/start.sh"]
    env_file:
      - redis.env
  cluster-redis-3:
    image: redis:6.2.13
    container_name: cluster-redis-3
#    restart: always
    ports:
      - 7363:7363
      - 17363:17363
    networks:
      - kylin-net
    volumes:
      - redis_3_data:/data
      - ./conf/node-3/conf:/opt/redis/conf
      - ./bin:/opt/redis/bin
    command: ["/opt/redis/bin/start.sh"]
    env_file:
      - redis.env
  cluster-redis-4:
    image: redis:6.2.13
    container_name: cluster-redis-4
#    restart: always
    ports:
      - 7364:7364
      - 17364:17364
    networks:
      - kylin-net
    volumes:
      - redis_4_data:/data
      - ./conf/node-4/conf:/opt/redis/conf
      - ./bin:/opt/redis/bin
    command: ["/opt/redis/bin/start.sh"]
    env_file:
      - redis.env
  cluster-redis-5:
    image: redis:6.2.13
    container_name: cluster-redis-5
#    restart: always
    ports:
      - 7365:7365
      - 17365:17365
    networks:
      - kylin-net
    volumes:
      - redis_5_data:/data
      - ./conf/node-5/conf:/opt/redis/conf
      - ./bin:/opt/redis/bin
    command: ["/opt/redis/bin/start.sh"]
    env_file:
      - redis.env
  cluster-redis-6:
    image: redis:6.2.13
    container_name: cluster-redis-6
#    restart: always
    ports:
      - 7366:7366
      - 17366:17366
    networks:
      - kylin-net
    volumes:
      - redis_6_data:/data
      - ./conf/node-6/conf:/opt/redis/conf
      - ./bin:/opt/redis/bin
    command: ["/opt/redis/bin/start.sh"]
    env_file:
      - redis.env

volumes:
  redis_1_data:
    driver: local
  redis_2_data:
    driver: local
  redis_3_data:
    driver: local
  redis_4_data:
    driver: local
  redis_5_data:
    driver: local
  redis_6_data:
    driver: local

networks:
  kylin-net:
    driver: bridge
    name: kylin-net