spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kp?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    hiddenmethod:
      filter:
        enabled: true
  messages:
    basename: static/i18n/messages
feign:
  sentinel:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  #      base-path: "/manage"
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      enabled: true
    conditions:
      enabled: true
    info:
      enabled: true
    beans:
      enabled: true
    auditevents:
      enabled: true
    prometheus:
      enabled: true
    mappings:
      enabled: true
    shutdown:
      enabled: true