spring:
  config:
    activate:
      on-profile: local
    import:
      - optional:nacos:plat-common.yaml
      - optional:nacos:plat-server-gateway-local.yaml
  cloud:
    sentinel:
      enabled: true # 是否开启。默认为 true 开启
      eager: true # 是否饥饿加载。默认为 false 关闭
      transport:
        dashboard: localhost:8080 # 控制台
#        port: 8719
#        clientIp: 127.0.0.1 #指定和控制台通信的IP，若不配置，会自动选择一个IP注册

    nacos:
      config:
        server-addr: 127.0.0.1:8848
        namespace: local
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: local
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: url-proxy-1
          uri: lb://plat-server-core
          predicates:
            - Path=/k-plat/core/**
          filters:
            - StripPrefix=1
            - AddTrace
            - AddRequestHeader=K-FROM,plat-server-gateway
            - AddResponseHeader=K-FROM, plat-server-gateway
            - AddRequestParameter=K-FROM,plat-server-gateway
          metadata:
            connect-timeout: 10000 #ms
            response-timeout: 10000 #ms
        - id: url-proxy-2
          uri: lb://plat-server-core
          predicates:
            - Path=/kplat/core-proxy/**
          filters:
            - StripPrefix=1
            - AddTrace
            - AddRequestHeader=K-FROM,plat-server-gateway
            - AddResponseHeader=K-FROM, plat-server-gateway
            - AddRequestParameter=K-FROM,plat-server-gateway
            - SetRequestHeader=K-CLIENT, plat-server-gateway
            - PreserveHostHeader
            - RequestSize=200
            - RewritePath=/core-proxy/?(?<segment>.*), /core/$\{segment}
            - SaveSession
            - SecureHeaders

          metadata:
            connect-timeout: 10000 #ms
            response-timeout: 10000 #ms
        - id: url-proxy-3
          uri: lb://plat-server-core
          predicates:
            - Path=/kp/core/**
            - After=2022-02-26T13:00:00+08:00[Asia/Shanghai]
            - Cookie=testCookie, \d+
            - Header=testHeader, \d+
            - Method=GET,POST
            - Query=testParm,\d+
#            - RemoteAddr=172.25.1.1/16
            - RemoteAddr=127.0.0.1
            - Host=127.0.0.1*
          filters:
            - StripPrefix=1
            - AddTrace
            - AddRequestHeader=K-FROM,plat-server-gateway
            - AddResponseHeader=K-FROM, plat-server-gateway
            - AddRequestParameter=K-FROM,plat-server-gateway
            - SetRequestHeader=K-CLIENT, plat-server-gateway
          metadata:
            connect-timeout: 10000 #ms
            response-timeout: 10000 #ms
        - id: url-proxy-4
          uri: http://127.0.0.1:8101
          predicates:
            - Path=/mdc/core/**
#            - DCRouter=1
            - Weight=group1, 75
          filters:
            - StripPrefix=1
            - AddTrace
            - AddResponseHeader=K-FROM, plat-server-gateway
            - AddRequestParameter=K-FROM,plat-server-gateway
          metadata:
            connect-timeout: 10000 #ms
            response-timeout: 10000 #ms
        - id: url-proxy-5
          uri: http://127.0.0.1:8201
          predicates:
            - Path=/mdc/core/**
#            - DCRouter=2
            - Weight=group1, 25
          filters:
            - StripPrefix=1
            - AddTrace
            - AddResponseHeader=K-FROM, plat-server-gateway
            - AddRequestParameter=K-FROM,plat-server-gateway
          metadata:
            connect-timeout: 10000 #ms
            response-timeout: 10000 #ms