spring:
  config:
    activate:
      on-profile: local
    import:
      - optional:nacos:plat-common.yaml
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        namespace: local

      discovery:
        server-addr: 127.0.0.1:8848
        namespace: local
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
#    cluster:
#      nodes:
#        - 192.168.0.105:7361
#        - 192.168.0.105:7362
#        - 192.168.0.105:7363
#        - 192.168.0.105:7364
#        - 192.168.0.105:7365
#        - 192.168.0.105:7366
    lettuce:
      pool:
        # 连接池中的最大空闲连接 默认8
        max-idle: 8
        # 连接池中的最小空闲连接 默认0
        min-idle: 0
        # 连接池最大连接数 默认8 ，负数表示没有限制
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
        max-wait: -1
    timeout: 30000