version: '3.5'

services:
  kafka:
    image: bitnami/kafka:3.3.2
    ports:
      - "9092:9092"
    networks:
      - kylin-net
    volumes:
      - "kafka_data:/bitnami"
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=INTERNAL://:19092,CONTROLLER://:9093,EXTERNAL://0.0.0.0:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://:19092,EXTERNAL://${KAFKA_ADVERTISED_LISTENERS_IP}:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
  kafka-ui:
    image: provectuslabs/kafka-ui
    ports:
      - "9093:8080"
    networks:
      - kylin-net
    depends_on:
      - kafka
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:19092
volumes:
  kafka_data:
    driver: local

networks:
  kylin-net:
    driver: bridge
    name: kylin-net