use kp;
CREATE TABLE IF NOT EXISTS `kb_doc` (
    `id` varchar(64) NOT NULL COMMENT '主键',
    `sys_tenant_id` varchar(64) NOT NULL DEFAULT '' COMMENT '租户ID',
    `sys_auto_updated` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '系统更新时间',
    `sys_created_user_id` varchar(64) NOT NULL default 0 COMMENT '创建人userid',
    `sys_created_user_name` varchar(64) NOT NULL default '' COMMENT '创建人username',
    `sys_created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `sys_update_user_id` varchar(64) NOT NULL default 0 COMMENT '最后编辑人userid',
    `sys_update_user_name` varchar(64) NOT NULL default '' COMMENT '最后编辑人username',
    `sys_update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '最后编辑时间',
    `sys_delete_flag` tinyint  NOT NULL DEFAULT 0 COMMENT '0 未删除 1删除',
    `sys_op_lock` int NULL COMMENT '乐观锁',
    `type` tinyint NOT NULL DEFAULT 0 COMMENT '类型',
    `title` varchar(256) NOT NULL DEFAULT '' COMMENT 'title',
    `content` MEDIUMTEXT NOT NULL  COMMENT 'content',
    `summary` varchar(1024) NOT NULL DEFAULT '' COMMENT 'summary',
    `keywords` varchar(1024) NOT NULL DEFAULT '' COMMENT 'keywords',
    `tags` varchar(1024) NOT NULL DEFAULT '' COMMENT 'tags',
    `md5` varchar(64) NOT NULL DEFAULT '' COMMENT 'md5',
    `version` DECIMAL(10, 1) NOT NULL DEFAULT 0 COMMENT '版本号',
    `status` tinyint NOT NULL DEFAULT 0 COMMENT '状态',
    `description` varchar(255) NOT NULL DEFAULT '' COMMENT '描述',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uniq_doc` (`md5`) COMMENT '唯一的code'
);