version: '3'
services:
  redis-1:
    image: redis:6.2.13
    container_name: redis-1
    restart: always
    network_mode: "host" #host：容器环境不隔离，将使用主机的端口和ip，不能与ports 端口映射同时使用
    volumes:
      - /Users/bijian/software/redis/cluster/node-1/data:/data
      - /Users/bijian/software/redis/cluster/node-1/conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server","/usr/local/etc/redis/redis.conf"]
  redis-2:
    image: redis:6.2.13
    container_name: redis-2
    restart: always
    network_mode: "host" #host：容器环境不隔离，将使用主机的端口和ip，不能与ports 端口映射同时使用
    volumes:
      - /Users/bijian/software/redis/cluster/node-2/data:/data
      - /Users/bijian/software/redis/cluster/node-2/conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server","/usr/local/etc/redis/redis.conf" ]
  redis-3:
    image: redis:6.2.13
    container_name: redis-3
    restart: always
    network_mode: "host" #host：容器环境不隔离，将使用主机的端口和ip，不能与ports 端口映射同时使用
    volumes:
      - /Users/bijian/software/redis/cluster/node-3/data:/data
      - /Users/bijian/software/redis/cluster/node-3/conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server","/usr/local/etc/redis/redis.conf" ]
  redis-4:
    image: redis:6.2.13
    container_name: redis-4
    restart: always
    network_mode: "host" #host：容器环境不隔离，将使用主机的端口和ip，不能与ports 端口映射同时使用
    volumes:
      - /Users/bijian/software/redis/cluster/node-4/data:/data
      - /Users/bijian/software/redis/cluster/node-4/conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server","/usr/local/etc/redis/redis.conf" ]
  redis-5:
    image: redis:6.2.13
    container_name: redis-5
    restart: always
    network_mode: "host" #host：容器环境不隔离，将使用主机的端口和ip，不能与ports 端口映射同时使用
    volumes:
      - /Users/bijian/software/redis/cluster/node-5/data:/data
      - /Users/bijian/software/redis/cluster/node-5/conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server","/usr/local/etc/redis/redis.conf" ]
  redis-6:
    image: redis:6.2.13
    container_name: redis-6
    restart: always
    network_mode: "host" #host：容器环境不隔离，将使用主机的端口和ip，不能与ports 端口映射同时使用
    volumes:
      - /Users/bijian/software/redis/cluster/node-6/data:/data
      - /Users/bijian/software/redis/cluster/node-6/conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server","/usr/local/etc/redis/redis.conf" ]