spring:
  config:
    activate:
      on-profile: local
    import:
      - optional:nacos:plat-common.yaml
      - optional:nacos:plat-server-core-local.yaml
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        namespace: baa83f28-72ee-416a-97b5-b9de328b87ea

      discovery:
        server-addr: 127.0.0.1:8848
        namespace: baa83f28-72ee-416a-97b5-b9de328b87ea
